name: Environment variables
on: push
env:
  EXAMPLE: Defined by job level
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${EXAMPLE}"
      - env:
          EXAMPLE: Defined by step level
        run: echo "${EXAMPLE}"
      - uses: actions/checkout@v4
        with:
          ref: ${{ env.EXAMPLE }}
