name: Multi-dimension matrix
on: push
jobs:
  print:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        node_version: [18, 20]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node_version }}
      - run: echo "${RUNNER_OS}" && node --version
